displayName=Sleepwalker Stakeout
author=Suspext
description=Displays a Blisterwood stake sprite as a fake XP drop when one is thrown
tags=phosani,nightmare,sleepwalker,blisterwood,stake,pnm,bossing,fake,xp,drop
version=1.0.0
plugins=com.sleepwalkerstakeout.SleepwalkerStakeoutPlugin
build=standard