displayName=Sleepwalker Stakeout
author=Suspext
description=Displays weapon sprites as fake XP drops when attacking Sleepwalkers
tags=phosani,nightmare,pnm,sleepwalker,blisterwood,stake,ayak,blowpipe,bow,dart,boss,fake,xp,drop
version=1.1.0
plugins=com.sleepwalkerstakeout.SleepwalkerStakeoutPlugin
build=standard