displayName=Sleepwalker Stakeout
author=Suspext
description=Weapon sprites as fake XP drops
tags=phosani,nightmare,pnm,sleepwalker,blisterwood,stake,ayak,blowpipe,bow,dart,boss,fake,xp,drop,tag,npc
version=1.2.0
plugins=com.sleepwalkerstakeout.SleepwalkerStakeoutPlugin
build=standard